"""added number location address in pickup

Revision ID: 7dd1df3bc17f
Revises: 
Create Date: 2025-03-03 00:13:59.934991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd1df3bc17f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_number', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('pickup_location', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup', schema=None) as batch_op:
        batch_op.drop_column('pickup_location')
        batch_op.drop_column('pickup_number')

    # ### end Alembic commands ###
